---
title: "Untitled"
author: "Alex Sciacca"
date: '2022-06-24'
output: html_document
---

```{r}
library(tidyverse)
library(cluster)
library(factoextra)
library(dendextend)
```
```{r}
trucks=read_csv("~/School/BAN502/Module 6/trucks-1.csv")
```
```{r}
trucks = trucks %>% select(-Driver_ID) %>% 
  drop_na() #row-wise deletion of missingness
str(trucks)
summary(trucks)
```
```{r}
ggplot(trucks, aes(x=Distance, y=Speeding)) +
  geom_point(alpha = 0.4) + theme_bw()
```
```{r}
kmeans_recipe = recipe(~ Distance + Speeding, trucks) 

truck_dummy = kmeans_recipe %>% 
  step_scale(all_numeric()) %>%
  step_center(all_numeric()) 

truck_dummy = prep(truck_dummy, trucks)

trucks_cleaned = bake(truck_dummy, trucks) #applies the recipe and yields a data frame
```

```{r}
#we have two data frames now, one scaled and dummied and one with just row-wise deletion of missingness
summary(trucks_cleaned)
summary(trucks)
```
```{r}
set.seed(64)
clusts = 
  tibble(k = 2) %>%
  mutate(
    kclust = map(k, ~kmeans(trucks_cleaned, .x)),
    tidied = map(kclust, tidy),
    glanced = map(kclust, glance),
    augmented = map(kclust, augment, trucks)
  )

clusts
```
```{r}
clusters = 
  clusts %>%
  unnest(cols = c(tidied))

assignments = 
  clusts %>% 
  unnest(cols = c(augmented))

clusterings = 
  clusts %>%
  unnest(cols = c(glanced))
```

```{r}
p1 = 
  ggplot(assignments, aes(x = Distance, y = Speeding)) +
  geom_point(aes(color = .cluster), alpha = 0.8) + 
  facet_wrap(~ k)
p1
```
```{r}
set.seed(412)
clusts = 
  tibble(k = 1:8) %>%
  mutate(
    kclust = map(k, ~kmeans(trucks_cleaned, .x)),
    tidied = map(kclust, tidy),
    glanced = map(kclust, glance),
    augmented = map(kclust, augment, trucks)
  )

clusts
```

```{r}
clusters = 
  clusts %>%
  unnest(cols = c(tidied))

assignments = 
  clusts %>% 
  unnest(cols = c(augmented))

clusterings = 
  clusts %>%
  unnest(cols = c(glanced))
```

```{r}
p1 = 
  ggplot(assignments, aes(x = Distance, y = Speeding)) +
  geom_point(aes(color = .cluster), alpha = 0.8) + 
  facet_wrap(~ k)
p1
```

```{r}
ggplot(clusterings, aes(k, tot.withinss)) +
  geom_line() +
  geom_point() + theme_bw()
```


```{r}
trucks_scaled = scale(trucks) 
summary(trucks_scaled)
#scale works by calculating the mean and standard deviation of the entire variable, then scales each element by subtracting the mean and dividing by the standard deviation  
```

```{r}
trucks_clust = kmeans(trucks_scaled, centers = 3) #run k-means clustering with k = 4
trucks_clust #view results
```

```{r}
set.seed(64)
clusts = 
  tibble(k = 4) %>%
  mutate(
    kclust = map(k, ~kmeans(trucks_cleaned, .x)),
    tidied = map(kclust, tidy),
    glanced = map(kclust, glance),
    augmented = map(kclust, augment, trucks)
  )

clusts
```

```{r}
clusters = 
  clusts %>%
  unnest(cols = c(tidied))

assignments = 
  clusts %>% 
  unnest(cols = c(augmented))

clusterings = 
  clusts %>%
  unnest(cols = c(glanced))
```

```{r}
p1 = 
  ggplot(assignments, aes(x = Distance, y = Speeding)) +
  geom_point(aes(color = .cluster), alpha = 0.8) + 
  facet_wrap(~ k)
p1
```